#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Vorbe's Cloudflare Worker fallback (last resort if OpenRouter and
# Groq both fail). Uses npx for wrangler so nothing needs a global install.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Cloudflare Worker fallback for Vorbe"

# ── Stage 1: prerequisites ─────────────────────────────────────────────────
stage "Prerequisites"
say "This uses Cloudflare Workers AI's free tier - 10,000 neurons/day, no"
say "paid Workers plan needed. wrangler and vercel run via npx below, so"
say "nothing needs installing globally."
if ! command -v node >/dev/null 2>&1; then
  warn "node isn't on PATH - install Node.js first (https://nodejs.org), then re-run this script."
  exit 1
fi
note "node: $(node --version)"
if confirm "Do you already have a Cloudflare account?"; then
  note "good, moving on"
else
  open_url "https://dash.cloudflare.com/sign-up"
  step "Sign up (free) - no card required for Workers AI's free tier."
  pause "Done? Press Enter to continue."
fi

# ── Stage 2: Cloudflare login ────────────────────────────────────────────
stage "Log in to Cloudflare from the CLI"
say "This opens a browser to authorize wrangler (Cloudflare's CLI) against"
say "your account. It only needs to happen once."
pause "Press Enter to run 'wrangler login'..."
npx --yes wrangler login || warn "login may not have completed - if the next stage fails, re-run this script."

# ── Stage 3: scaffold the worker ─────────────────────────────────────────
stage "Create the worker project"
say "Writing cloudflare-fallback/ with the worker code and a fresh auth token."

mkdir -p cloudflare-fallback/src

COMPAT_DATE=$(date -u +%F)
AUTH_TOKEN=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")

cat > cloudflare-fallback/wrangler.toml <<TOML
name = "vorbe-fallback"
main = "src/index.js"
compatibility_date = "${COMPAT_DATE}"

[ai]
binding = "AI"
TOML

cat > cloudflare-fallback/src/index.js <<'WORKER'
// Vorbe's last-resort AI fallback. Only reached from api_server.py if every
// OpenRouter model (primary + backup) AND Groq have failed - runs on
// Cloudflare's own infrastructure, independent of both.
export default {
  async fetch(request, env) {
    if (request.method !== "POST") {
      return new Response("Method not allowed", { status: 405 });
    }

    const auth = request.headers.get("Authorization");
    if (!env.WORKER_AUTH_TOKEN || auth !== `Bearer ${env.WORKER_AUTH_TOKEN}`) {
      return new Response("Unauthorized", { status: 401 });
    }

    let body;
    try {
      body = await request.json();
    } catch {
      return new Response("Invalid JSON body", { status: 400 });
    }

    const { system, prompt, max_tokens } = body;
    if (!prompt) {
      return new Response("Missing 'prompt'", { status: 400 });
    }

    try {
      const result = await env.AI.run("@cf/qwen/qwen2.5-coder-32b-instruct", {
        messages: [
          {
            role: "system",
            content: system || "You are a helpful Luau programming assistant for the Vortex game platform.",
          },
          { role: "user", content: prompt },
        ],
        max_tokens: max_tokens || 800,
      });

      // OpenAI-shaped response so api_server.py parses it the same way as
      // the OpenRouter/Groq responses.
      return Response.json({
        choices: [{ message: { content: result.response } }],
      });
    } catch (err) {
      return new Response(`Workers AI error: ${err.message}`, { status: 502 });
    }
  },
};
WORKER

printf '  %s✓ wrote%s cloudflare-fallback/wrangler.toml and src/index.js\n' "$GREEN" "$RESET"

# ── Stage 4: set the worker's secret and deploy ──────────────────────────
stage "Set the worker's auth secret and deploy"
say "The worker only accepts requests carrying this token, so nobody else"
say "can call your Workers AI allowance."
(
  cd cloudflare-fallback
  printf '%s' "$AUTH_TOKEN" | npx --yes wrangler secret put WORKER_AUTH_TOKEN
) || { warn "couldn't set the worker secret - fix the error above, then re-run this script."; exit 1; }
printf '  %s✓ set%s the worker secret\n' "$GREEN" "$RESET"

say "Deploying..."
DEPLOY_OUTPUT=$(cd cloudflare-fallback && npx --yes wrangler deploy 2>&1) || {
  printf '%s\n' "$DEPLOY_OUTPUT"
  warn "deploy failed - see the output above, fix it, then re-run this script."
  exit 1
}
printf '%s\n' "$DEPLOY_OUTPUT"

WORKER_URL=$(printf '%s' "$DEPLOY_OUTPUT" | grep -oE 'https://[a-zA-Z0-9.-]+\.workers\.dev' | head -1) || true
if [[ -z "$WORKER_URL" ]]; then
  warn "couldn't find the deployed URL in wrangler's output - copy it from above."
  ask WORKER_URL "Paste the deployed worker URL:"
fi

write_env CLOUDFLARE_WORKER_TOKEN "$AUTH_TOKEN"
write_env CLOUDFLARE_WORKER_URL "$WORKER_URL"

# ── Stage 5: wire it into Vercel ─────────────────────────────────────────
stage "Add the fallback to Vercel"
say "Vorbe's api_server.py reads these two production env vars. This project"
say "isn't linked to the Vercel CLI here, so add them through the dashboard -"
say "it's the same place GROQ_API_KEY and OPENROUTER_API_KEY already live."
open_url "https://vercel.com/dashboard"
step "Open your Vorbe project → Settings → Environment Variables → Add New."
step "Name: CLOUDFLARE_WORKER_URL   Value: ${WORKER_URL}   Environment: Production"
step "Add New again."
step "Name: CLOUDFLARE_WORKER_TOKEN   Value: ${AUTH_TOKEN}   Environment: Production"
note "(both values are also saved in .env for local dev via 'vercel dev')"
warn "Vercel only picks up new env vars on the NEXT deploy - redeploy after adding these"
step "  (Deployments tab → ⋯ on the latest deployment → Redeploy), or just push a commit."
pause "Added both? Press Enter to continue."

# ── Stage 6: verify it actually works ────────────────────────────────────
stage "Verify"
say "Calling the deployed worker directly, the same way api_server.py will."
VERIFY_BODY=$(node -e "console.log(JSON.stringify({system:'You are terse.', prompt:'Say OK.', max_tokens:20}))")
VERIFY_RESPONSE=$(curl -s -X POST "$WORKER_URL" \
  -H "Authorization: Bearer $AUTH_TOKEN" \
  -H "Content-Type: application/json" \
  -d "$VERIFY_BODY") || true
printf '  response: %s\n' "$VERIFY_RESPONSE"
if printf '%s' "$VERIFY_RESPONSE" | grep -q '"content"'; then
  printf '  %s✓ the worker responded correctly%s\n' "$GREEN" "$RESET"
else
  warn "that doesn't look like a successful response - check the worker logs (npx wrangler tail, from cloudflare-fallback/) if this keeps happening."
fi

finish
note "Next: ask Claude to wire CLOUDFLARE_WORKER_URL/CLOUDFLARE_WORKER_TOKEN into"
note "api_server.py's fallback chain, if it hasn't already."
